version: '3.4'
name: task-scheduler
services:
  
#  rabbitmq:
#    image: rabbitmq:3.10.7-management
#    ports:
#      - 15672:15672

  redis:
    image: redis
    container_name: redis-tasks
    restart: unless-stopped
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf
